[package]
name = "laterbase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = "0.7.0"
ulid = "1.0.0"
uuid = { version = "1.4.0", features = ["v4"] }

[dev-dependencies]
proptest = "1.0.0"
